import type { TemplateCategory } from "@/generated/prisma/enums";

export const CATEGORY_LABELS: Record<TemplateCategory, string> = {
  GERAL: "Geral",
  PRIMEIRO_EMPREGO: "Primeiro Emprego",
  RECEM_FORMADO: "Recém-formado",
  ADMINISTRATIVO: "Administrativo",
  CONTABILIDADE: "Contabilidade",
  RECURSOS_HUMANOS: "Recursos Humanos",
  SAUDE: "Saúde",
  ENFERMAGEM: "Enfermagem",
  OPTOMETRIA: "Optometria",
  EDUCACAO: "Educação",
  ENGENHARIA: "Engenharia",
  INFORMATICA: "Informática",
  MARKETING: "Marketing",
  VENDAS: "Vendas",
  VENDAS_MARKETING: "Vendas / Marketing",
  ATENDIMENTO_CLIENTE: "Atendimento ao Cliente",
  GESTAO: "Gestão",
  FINANCAS: "Finanças",
  CONSTRUCAO: "Construção",
  LOGISTICA: "Logística",
  HOTELARIA: "Hotelaria",
  MOTORISTA: "Motorista",
  TECNICO_PROFISSIONAL: "Técnico Profissional",
  EXECUTIVO: "Executivo",
};

/** Ordem de apresentação dos filtros (as categorias sem modelos ativos são ocultadas). */
export const CATEGORY_ORDER: TemplateCategory[] = [
  "PRIMEIRO_EMPREGO",
  "RECEM_FORMADO",
  "ADMINISTRATIVO",
  "CONTABILIDADE",
  "RECURSOS_HUMANOS",
  "SAUDE",
  "ENFERMAGEM",
  "OPTOMETRIA",
  "EDUCACAO",
  "ENGENHARIA",
  "INFORMATICA",
  "MARKETING",
  "VENDAS",
  "ATENDIMENTO_CLIENTE",
  "GESTAO",
  "FINANCAS",
  "CONSTRUCAO",
  "LOGISTICA",
  "HOTELARIA",
  "MOTORISTA",
  "TECNICO_PROFISSIONAL",
  "EXECUTIVO",
  "GERAL",
  "VENDAS_MARKETING",
];
